swagger: "2.0"
info:
  title: WalletNode REST API
  version: "1.0"
host: localhost:8080
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /artworks/register:
    post:
      tags:
      - artworks
      summary: Registers a new artwork
      description: Runs a new registration process for the new artwork.
      operationId: artworks#register
      parameters:
      - name: RegisterRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/ArtworksRegisterRequestBody'
          required:
          - artist_name
          - name
          - issued_copies
          - image_id
          - artist_pastelid
          - spendable_address
          - network_fee
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/ArtworksRegisterResponseBody'
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/ArtworksRegisterBadRequestResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ArtworksRegisterInternalServerErrorResponseBody'
      schemes:
      - http
  /artworks/register/{jobId}:
    get:
      tags:
      - artworks
      summary: Returns a status of the registration artwork
      description: Streams statuses of the artwork registration.
      operationId: artworks#registerStatus
      parameters:
      - name: jobId
        in: path
        description: Job ID of the registration process
        required: true
        type: integer
        minimum: 1
      responses:
        "101":
          description: Switching Protocols response.
          schema:
            $ref: '#/definitions/ArtworksRegisterStatusResponseBody'
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/ArtworksRegisterStatusBadRequestResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/ArtworksRegisterStatusNotFoundResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ArtworksRegisterStatusInternalServerErrorResponseBody'
      schemes:
      - ws
  /artworks/register/upload-image:
    post:
      tags:
      - artworks
      summary: Uploads an image
      description: Upload the image that is used when registering a new artwork.
      operationId: artworks#uploadImage
      consumes:
      - multipart/form-data
      parameters:
      - name: UploadImageRequestBody
        in: formData
        required: true
        schema:
          $ref: '#/definitions/ArtworksUploadImageRequestBody'
          required:
          - file
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/ArtworksUploadImageResponseBody'
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/ArtworksUploadImageBadRequestResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ArtworksUploadImageInternalServerErrorResponseBody'
      schemes:
      - http
definitions:
  ArtworksRegisterBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: register_BadRequest_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ArtworksRegisterInternalServerErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: register_InternalServerError_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ArtworksRegisterRequestBody:
    title: ArtworksRegisterRequestBody
    type: object
    properties:
      artist_name:
        type: string
        description: Name of the artist
        example: Leonardo da Vinci
        maxLength: 256
      artist_pastelid:
        type: string
        description: Artist's PastelID
        example: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
        pattern: ^[a-zA-Z0-9]+$
        minLength: 86
        maxLength: 86
      artist_website_url:
        type: string
        description: Artist website URL
        example: https://www.leonardodavinci.net
        maxLength: 256
      description:
        type: string
        description: Description of the artwork
        example: The Mona Lisa is an oil painting by Italian artist, inventor, and
          writer Leonardo da Vinci. Likely completed in 1506, the piece features a
          portrait of a seated woman set against an imaginary landscape.
        maxLength: 1024
      image_id:
        type: string
        description: Uploaded image ID
        example: d93lsd02
        pattern: ^[a-zA-Z0-9]+$
        minLength: 8
        maxLength: 8
      issued_copies:
        type: integer
        description: Number of copies issued
        default: 1
        example: 1
        minimum: 1
        maximum: 1000
      keywords:
        type: string
        description: Keywords
        example: Renaissance, sfumato, portrait
        maxLength: 256
      name:
        type: string
        description: Name of the artwork
        example: Mona Lisa
        maxLength: 256
      network_fee:
        type: number
        default: 1
        example: 100
        minimum: 1e-05
      series_name:
        type: string
        description: Series name
        example: Famous artist
        maxLength: 256
      spendable_address:
        type: string
        description: Spendable address
        example: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
        pattern: ^[a-zA-Z0-9]+$
        minLength: 35
        maxLength: 35
      youtube_url:
        type: string
        description: Artwork creation video youtube URL
        example: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
        maxLength: 128
    example:
      artist_name: Leonardo da Vinci
      artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
      artist_website_url: https://www.leonardodavinci.net
      description: The Mona Lisa is an oil painting by Italian artist, inventor, and
        writer Leonardo da Vinci. Likely completed in 1506, the piece features a portrait
        of a seated woman set against an imaginary landscape.
      image_id: d93lsd02
      issued_copies: 1
      keywords: Renaissance, sfumato, portrait
      name: Mona Lisa
      network_fee: 100
      series_name: Famous artist
      spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
      youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
    required:
    - artist_name
    - name
    - issued_copies
    - image_id
    - artist_pastelid
    - spendable_address
    - network_fee
  ArtworksRegisterResponseBody:
    title: 'Mediatype identifier: application/vnd.artwork.register; view=default'
    type: object
    properties:
      job_id:
        type: integer
        description: Job ID of the registration process
        example: 5
        format: int64
    description: RegisterResponseBody result type (default view)
    example:
      job_id: 5
    required:
    - job_id
  ArtworksRegisterStatusBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: registerStatus_BadRequest_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ArtworksRegisterStatusInternalServerErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: registerStatus_InternalServerError_response_body result type (default
      view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ArtworksRegisterStatusNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: registerStatus_NotFound_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ArtworksRegisterStatusResponseBody:
    title: 'Mediatype identifier: application/vnd.artwork.register.job; view=default'
    type: object
    properties:
      id:
        type: integer
        description: JOb ID of the registration process
        example: 5
        format: int64
      status:
        type: string
        description: Status of the registration process
        example: Registration started
      txid:
        type: string
        description: txid
        example: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
        minLength: 64
        maxLength: 64
    description: RegisterStatusResponseBody result type (default view)
    example:
      id: 5
      status: Registration started
      txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
    required:
    - id
    - status
  ArtworksUploadImageBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: uploadImage_BadRequest_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ArtworksUploadImageInternalServerErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: uploadImage_InternalServerError_response_body result type (default
      view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ArtworksUploadImageRequestBody:
    title: ArtworksUploadImageRequestBody
    type: object
    properties:
      file:
        type: string
        description: File to upload
        example:
        - 79
        - 112
        - 116
        - 105
        - 111
        - 32
        - 111
        - 100
        - 105
        - 111
        - 46
        format: byte
    example:
      file:
      - 85
      - 116
      - 32
      - 118
      - 101
      - 108
      - 32
      - 101
      - 116
      - 46
    required:
    - file
  ArtworksUploadImageResponseBody:
    title: 'Mediatype identifier: application/vnd.artwork.upload-image; view=default'
    type: object
    properties:
      expires_in:
        type: string
        description: Image expiration
        example: "2019-10-12T07:20:50.52Z"
        format: date-time
      image_id:
        type: string
        description: Uploaded image ID
        example: d93lsd02
        minLength: 8
        maxLength: 8
    description: UploadImageResponseBody result type (default view)
    example:
      expires_in: "2019-10-12T07:20:50.52Z"
      image_id: d93lsd02
    required:
    - image_id
    - expires_in
