openapi: 3.0.3
info:
  title: WalletNode REST API
  version: "1.0"
servers:
- url: http://localhost:8080
paths:
  /artworks/register:
    get:
      tags:
      - artworks
      summary: Returns list of tasks
      description: List of all tasks.
      operationId: artworks#registerTasks
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponseTinyCollection'
              example:
              - id: 5
                status: Registration Started
                txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
              - id: 5
                status: Registration Started
                txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
    post:
      tags:
      - artworks
      summary: Registers a new artwork
      description: Runs a new registration process for the new artwork.
      operationId: artworks#register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequestBody'
            example:
              artist_name: Leonardo da Vinci
              artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
              artist_website_url: https://www.leonardodavinci.net
              description: The Mona Lisa is an oil painting by Italian artist, inventor,
                and writer Leonardo da Vinci. Likely completed in 1506, the piece
                features a portrait of a seated woman set against an imaginary landscape.
              image_id: 1
              issued_copies: 1
              keywords: Renaissance, sfumato, portrait
              name: Mona Lisa
              network_fee: 100
              series_name: Famous artist
              spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
              youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
      responses:
        "201":
          description: Created response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResult'
              example:
                task_id: 5
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /artworks/register/{taskId}:
    get:
      tags:
      - artworks
      summary: Find task by ID
      description: Returns a single task.
      operationId: artworks#registerTask
      parameters:
      - name: taskId
        in: path
        description: Task ID of the registration process
        required: true
        schema:
          type: integer
          description: Task ID of the registration process
          example: 5
          minimum: 1
        example: 5
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterTaskResponseBody'
              example:
                id: 5
                states:
                - date: "2019-10-12T07:20:50.52Z"
                  status: Registration Started
                - date: "2019-10-12T07:20:50.52Z"
                  status: Registration Started
                - date: "2019-10-12T07:20:50.52Z"
                  status: Registration Started
                status: Registration Started
                ticket:
                  artist_name: Leonardo da Vinci
                  artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
                  artist_website_url: https://www.leonardodavinci.net
                  description: The Mona Lisa is an oil painting by Italian artist,
                    inventor, and writer Leonardo da Vinci. Likely completed in 1506,
                    the piece features a portrait of a seated woman set against an
                    imaginary landscape.
                  image_id: 1
                  issued_copies: 1
                  keywords: Renaissance, sfumato, portrait
                  name: Mona Lisa
                  network_fee: 100
                  series_name: Famous artist
                  spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
                  youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
                txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /artworks/register/{taskId}/state:
    get:
      tags:
      - artworks
      summary: Streams state by task ID
      description: Streams the state of the registration process.
      operationId: artworks#registerTaskState
      parameters:
      - name: taskId
        in: path
        description: Task ID of the registration process
        required: true
        schema:
          type: integer
          description: Task ID of the registration process
          example: 5
          minimum: 1
        example: 5
      responses:
        "101":
          description: Switching Protocols response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskState'
              example:
                date: "2019-10-12T07:20:50.52Z"
                status: Registration Started
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /artworks/register/upload:
    post:
      tags:
      - artworks
      summary: Uploads an image
      description: Upload the image that is used when registering a new artwork.
      operationId: artworks#uploadImage
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UploadImageRequestBody'
            example:
              file:
              - 86
              - 101
              - 108
              - 32
              - 118
              - 111
              - 108
              - 117
              - 112
              - 116
              - 97
              - 116
              - 101
              - 109
              - 32
              - 112
              - 114
              - 111
              - 118
              - 105
              - 100
              - 101
              - 110
              - 116
              - 32
              - 100
              - 111
              - 108
              - 111
              - 114
              - 105
              - 98
              - 117
              - 115
              - 46
      responses:
        "201":
          description: Created response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'
              example:
                expires_in: "2019-10-12T07:20:50.52Z"
                image_id: 1
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
components:
  schemas:
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: true
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    Image:
      type: object
      properties:
        expires_in:
          type: string
          description: Image expiration
          example: "2019-10-12T07:20:50.52Z"
          format: date-time
        image_id:
          type: integer
          description: Uploaded image ID
          example: 1
          format: int64
      example:
        expires_in: "2019-10-12T07:20:50.52Z"
        image_id: 1
      required:
      - image_id
      - expires_in
    RegisterRequestBody:
      type: object
      properties:
        artist_name:
          type: string
          description: Name of the artist
          example: Leonardo da Vinci
          maxLength: 256
        artist_pastelid:
          type: string
          description: Artist's PastelID
          example: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
          pattern: ^[a-zA-Z0-9]+$
          minLength: 86
          maxLength: 86
        artist_website_url:
          type: string
          description: Artist website URL
          example: https://www.leonardodavinci.net
          maxLength: 256
        description:
          type: string
          description: Description of the artwork
          example: The Mona Lisa is an oil painting by Italian artist, inventor, and
            writer Leonardo da Vinci. Likely completed in 1506, the piece features
            a portrait of a seated woman set against an imaginary landscape.
          maxLength: 1024
        image_id:
          type: integer
          description: Uploaded image ID
          example: 1
          minimum: 1
        issued_copies:
          type: integer
          description: Number of copies issued
          default: 1
          example: 1
          minimum: 1
          maximum: 1000
        keywords:
          type: string
          description: Keywords
          example: Renaissance, sfumato, portrait
          maxLength: 256
        name:
          type: string
          description: Name of the artwork
          example: Mona Lisa
          maxLength: 256
        network_fee:
          type: number
          default: 1
          example: 100
          minimum: 1e-05
        series_name:
          type: string
          description: Series name
          example: Famous artist
          maxLength: 256
        spendable_address:
          type: string
          description: Spendable address
          example: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
          pattern: ^[a-zA-Z0-9]+$
          minLength: 35
          maxLength: 35
        youtube_url:
          type: string
          description: Artwork creation video youtube URL
          example: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
          maxLength: 128
      example:
        artist_name: Leonardo da Vinci
        artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
        artist_website_url: https://www.leonardodavinci.net
        description: The Mona Lisa is an oil painting by Italian artist, inventor,
          and writer Leonardo da Vinci. Likely completed in 1506, the piece features
          a portrait of a seated woman set against an imaginary landscape.
        image_id: 1
        issued_copies: 1
        keywords: Renaissance, sfumato, portrait
        name: Mona Lisa
        network_fee: 100
        series_name: Famous artist
        spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
        youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
      required:
      - artist_name
      - name
      - issued_copies
      - image_id
      - artist_pastelid
      - spendable_address
      - network_fee
    RegisterResult:
      type: object
      properties:
        task_id:
          type: integer
          description: Task ID of the registration process
          example: 5
          format: int64
      example:
        task_id: 5
      required:
      - task_id
    RegisterTaskResponseBody:
      type: object
      properties:
        id:
          type: integer
          description: JOb ID of the registration process
          example: 5
          format: int64
        states:
          type: array
          items:
            $ref: '#/components/schemas/TaskState'
          description: List of states from the very beginning of the process
          example:
          - date: "2019-10-12T07:20:50.52Z"
            status: Registration Started
          - date: "2019-10-12T07:20:50.52Z"
            status: Registration Started
        status:
          type: string
          description: Status of the registration process
          example: Registration Started
          enum:
          - Registration Started
          - Artwork Accepted
          - Waiting Activation
          - Activated
          - Error
        ticket:
          $ref: '#/components/schemas/RegisterRequestBody'
        txid:
          type: string
          description: txid
          example: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
          minLength: 64
          maxLength: 64
      description: RegisterTaskResponseBody result type (default view)
      example:
        id: 5
        states:
        - date: "2019-10-12T07:20:50.52Z"
          status: Registration Started
        - date: "2019-10-12T07:20:50.52Z"
          status: Registration Started
        - date: "2019-10-12T07:20:50.52Z"
          status: Registration Started
        status: Registration Started
        ticket:
          artist_name: Leonardo da Vinci
          artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
          artist_website_url: https://www.leonardodavinci.net
          description: The Mona Lisa is an oil painting by Italian artist, inventor,
            and writer Leonardo da Vinci. Likely completed in 1506, the piece features
            a portrait of a seated woman set against an imaginary landscape.
          image_id: 1
          issued_copies: 1
          keywords: Renaissance, sfumato, portrait
          name: Mona Lisa
          network_fee: 100
          series_name: Famous artist
          spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
          youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
        txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
      required:
      - id
      - status
      - ticket
    TaskResponseTiny:
      type: object
      properties:
        id:
          type: integer
          description: JOb ID of the registration process
          example: 5
          format: int64
        status:
          type: string
          description: Status of the registration process
          example: Registration Started
          enum:
          - Registration Started
          - Artwork Accepted
          - Waiting Activation
          - Activated
          - Error
        txid:
          type: string
          description: txid
          example: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
          minLength: 64
          maxLength: 64
      description: TaskResponse result type (tiny view)
      example:
        id: 5
        status: Registration Started
        txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
      required:
      - id
      - status
    TaskResponseTinyCollection:
      type: array
      items:
        $ref: '#/components/schemas/TaskResponseTiny'
      description: RegisterTasksResponseBody is the result type for an array of TaskResponse
        (tiny view)
      example:
      - id: 5
        status: Registration Started
        txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
      - id: 5
        status: Registration Started
        txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
    TaskState:
      type: object
      properties:
        date:
          type: string
          description: Date of the status creation
          example: "2019-10-12T07:20:50.52Z"
        status:
          type: string
          description: Status of the registration process
          example: Registration Started
          enum:
          - Registration Started
          - Artwork Accepted
          - Waiting Activation
          - Activated
          - Error
      example:
        date: "2019-10-12T07:20:50.52Z"
        status: Registration Started
      required:
      - date
      - status
    UploadImageRequestBody:
      type: object
      properties:
        file:
          type: string
          description: File to upload
          example:
          - 83
          - 117
          - 110
          - 116
          - 32
          - 97
          - 99
          - 99
          - 117
          - 115
          - 97
          - 110
          - 116
          - 105
          - 117
          - 109
          - 32
          - 105
          - 112
          - 115
          - 117
          - 109
          - 32
          - 116
          - 111
          - 116
          - 97
          - 109
          - 32
          - 101
          - 115
          - 116
          - 32
          - 117
          - 110
          - 100
          - 101
          - 46
          format: binary
      example:
        file:
        - 69
        - 105
        - 117
        - 115
        - 32
        - 99
        - 117
        - 109
        - 32
        - 104
        - 97
        - 114
        - 117
        - 109
        - 32
        - 105
        - 108
        - 108
        - 117
        - 109
        - 32
        - 118
        - 101
        - 108
        - 105
        - 116
        - 32
        - 118
        - 101
        - 110
        - 105
        - 97
        - 109
        - 46
      required:
      - file
